trigger:
- master

pool:
  vmImage: 'Ubuntu-latest'

variables:
  buildConfiguration: 'Release'

steps:
- task: NuGetToolInstaller@1

- task: NuGetCommand@2
  inputs:
    restoreSolution: '$(solution)'

- task: DotNetCoreCLI@2
  inputs:
    command: 'build'
    projects: 'SimpleWebHalloWorld/SimpleWebHalloWorld.csproj'

- task: DotNetCoreCLI@2
  inputs:
    command: 'test'
    projects: 'SimpleWebHalloWorld.Test/SimpleWebHalloWorld.Test/SimpleWebHalloWorld.Test.csproj'

- task: DotNetCoreCLI@2
  inputs:
    command: 'publish'
    publishWebProjects: true
    arguments: '--configuration $(buildConfiguration) --output out'
    zipAfterPublish: false

- task: Docker@2
  inputs:
    containerRegistry: 'ContainerTestAzure123'
    repository: 'sebbanjones1/azuredevopstest'
    command: 'buildAndPush'
    Dockerfile: '**/Dockerfile'
    tags: :$(Build.BuildID)


